name: CI/CD Deploy

on:
  push:
    paths-ignore:
      - '**.md'
      - '.git**'
    branches:
      - master
    
  workflow_dispatch:
  
  
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish
      run: dotnet publish ./kasu_uso.csproj -c Release -o publish

    - name: Inject API credential
      env:
        API_CREDENTIAL: ${{ secrets.API_CREDENTIAL }}
      run: | 
        echo -n "$API_CREDENTIAL" > publish/API.credential
        chmod 600 publish/API.credential

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: tukushityann.net
        username: hoge
        key: ${{ secrets.HOGE_SERVER }}
        source: "publish/"
        target: "/home/hoge/app/bin/Release/net8.0/publish/"
        strip_components: 1
        rm:  true

    - name: Restart service
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: tukushityann.net
        username: hoge
        key: ${{ secrets.HOGE_SERVER }}
        script: |
          sudo systemctl restart blazor-app
