name: CI/CD Deploy

on:
  push:
    paths-ignore:
      - '**.md'
      - '.git**'
    branches:
      - master
    
  workflow_dispatch:
  
  
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish
      run: dotnet publish ./kasu_uso.csproj -c Release -o publish

    - name: Inject API credential
      env:
        API_CREDENTIAL: ${{ secrets.API_CREDENTIAL }}
      run: | 
        echo -n "$API_CREDENTIAL" > publish/API_KEY.credential
        chmod 600 publish/API_KEY.credential

    - name: Validate OpenAI API Key
      run: |
        KEY=$(cat publish/API_KEY.credential)
        echo "▶️ Checking OpenAI API key…"
        status_code=$(
        curl -s -o /dev/null -w "%{http_code}" \
        https://api.openai.com/v1/models \
        -H "Authorization: Bearer $KEY"
        )
        if [ "$status_code" -eq 200 ]; then
          echo "✅ OpenAI API key is valid."
        else
          echo "❌ Invalid OpenAI API key (HTTP $status_code)." >&2
          exit 1
        fi

    - name: Copy files via SSH
      uses: appleboy/scp-action@v1
      with:
        host: tukushityann.net
        username: hoge
        key: ${{ secrets.HOGE_SERVER }}
        source: "publish/"
        target: "/home/hoge/app/bin/Release/net8.0/publish/"
        strip_components: 1
        rm:  true

    - name: Restart service
      uses: appleboy/ssh-action@v1
      with:
        host: tukushityann.net
        username: hoge
        key: ${{ secrets.HOGE_SERVER }}
        script: |
          sudo systemctl restart blazor-app
